# -*- coding: utf-8 -*-
"""Maria Eduarda Francklim - Lista 1 Monitoria Geoinfo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19JeE4AsOKy9RAJ-FE6GOag5NIGjrht91

#EXERCÍCIOS AULA 1 - LÓGICA DE PROGRAMAÇÃO E OPERADORES MATEMÁTICOS
"""

# OPERADORES MATEMÁTICOS
'Soma (+): Realiza a soma e retorna o resultado encontrado, ou adiciona um sinal de positivo ao número'
'Subtração (-): Realiza a subtração e retorna o resultado encontrado, ou adiciona um sinal de negativo ao número'
'Divisão (/): Realiza a divisão e retorna o resultado encontrado'
'Módulo (%): Realiza a divisão e retorna o resto'
'Divisão inteira (//): Realiza a divisão e retorna um valor inteiro'
'Multiplicação (*): Realiza a multiplicação e retorna o resultado encontrado'
'Potenciação (**): Realiza a potenciação, retorna o resultado encontrado'
'Raiz b de um valor (**(1/b)): Realiza a raiz de um valor. Se for raiz quadrada b=2, se for raiz cúbica b=3. Ex: raiz quadrada de 2 é 2**(1/2), raiz cúbica de 2 é 2**(1/3)...'
'= ( Atribui valor a uma variável)'
'== (Observa se dois valores são iguais)'
'> (Observa se o valor à esquerda do sinal é maior que o da direita)'
'< (Observa se o valor à esquerda do sinal é menor que o da direita)'
'>= (Observa se o valor à esquerda do sinal é maior ou igual que o da direita)'
'<= (Observa se o valor à esquerda do sinal é menor ou igual que o da direita)'
'!= (Observa se os dois valores são diferentes)'

# 1.  Escolha um valor para x e y, e substitua o _ por um operador matemático que satisfaça a equação x _ y = 15
x=3
y=5
print(x*y)

# 2. Encontre o erro no código abaixo e resolva.
6==5

# 3. Dados os valores de x,y,z; resolva as equações em uma única célula. Depois, classifique o resultado como um int ou float usando a função type().
# obs: é possível usar uma função dentro da outra, como por exemplo print(type(2)) ou print(1+2+3, type(1+2+3)).
x=10
y=25.5
z=13

print(x+y+z, type(x+y+z), y/x, type(y/x), z**y, type(z**y), x/z, type(x/z))

# 4. Dado as equações anteriores, encontre apenas valores inteiros. Depois encontre valores com até 2 casas decimais.
x=10
y=25.5
z=13

#ERRO:
#c=z**y
#if(c%1)==0: print(c)

print(round(x+y+z), round(y/x), round(z**y), round(x/z))
print(round(x+y+z,2), round(y/x,2), round(z**y,2), round(x/z,2))