# -*- coding: utf-8 -*-
"""Maria Eduarda Francklim - Lista exercícios 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Mnohzab1J5qkB1pV7uqsCX-UMsRDFo7

#Condicionais

or e and

#Estruturas de dados

Listas[], tuplas(), dicionários{}


obs: exercícios com input ganham ponto extra
"""

#Exemplo de input

lanches=input('digite o numero de pessoas:')
pessoas=int(lanches)
lanches_pessoas=2
total_lanches=pessoas*lanches_pessoas
paes=total_lanches
requeijao=int(total_lanches/10) + 1
salame=5*paes
fatias_tomate=paes*2
tomate=int(fatias_tomate/6) + 1
atum=int((paes + 1)/5)
banana=total_lanches
laranja=total_lanches


print('total de lanches:',total_lanches)
print('número de paes:',pessoas*2)
print('comprar:',requeijao,'potes')
print('comprar',salame,'fatias de salame')
print('comprar',atum, 'latas de atum')
print('numeros de tomates', tomate)
print('numero de bananas:',banana)
print('numero de laranjas:',laranja)
print('')
print('---Lanche de campo---')
print('')
print('Receita do MacGeo:')
print('Pao')
print('salame')
print('tomate')
print('Requeijao')
print('Pao')
print('')
print('Sobremesa:')
print('banana')
print('laranja')

#1. Crie uma lista de lanche para as atividades de campo para você e sua turma.
a=b=1
cacau=mel=leite=uva=lar=lim=tan=mar=mm=fc=laranja=tangerina=maverm=maverd=ban=am=pera=orig=pres=pizza=0
pessoas=int(input("Quantas pessoas têm na sua turma de campo?"))
quantppessoa=int(input("Um lanche é composto por: 1 caixinha de biscoito doce Belvita; 2 pacotinhos de biscoito salgado Clube Social; 2 garrafas de Gatorade; 1 fruta. Quantos lanches cada pessoa quer comer?"))
lanches=pessoas*quantppessoa
for a in range(1,lanches+1):
  print("Agora é a hora de escolher os sabores dos biscoitos doces, dos biscoitos salgados e das bebidas e a fruta. Vamos começar pelos biscoitos doces")
  biscoito=int(input("Para Belvita Cacau e Cereais, digite 1; para Belvita Mel e Cacau, digite 2; Belvita Leite e Aveia, digite 3"))
  while(biscoito!=1 and biscoito!=2 and biscoito!=3):
    print("Escolha inválida. Tente novamente")
    biscoito=int(input("Para Belvita Cacau e Cereais, digite 1; para Belvita Mel e Cacau, digite 2; Belvita Leite e Aveia, digite 3"))
  if(biscoito==1):
    print("Você escolheu Belvita Cacau e Cereais")
    cacau=cacau+1
  elif(biscoito==2):
    print("Você escolheu Belvita Mel e Cacau")
    mel=mel+1
  elif(biscoito==3):
    print("Você escolheu Belvita Leite e Aveia")
    leite=leite+1
  print("Agora é a hora de escolher os biscoitos salgados. Como são 2 pacotes, você vai ser perguntado 2 vezes sobre os sabores")
  club=int(input("Primeiro pacote. Para Clube Social Original, digite 1; para Clube Social Presunto, digite 2; para Clube Social Pizza, digite 3"))
  for b in range(1,2):
    while(club!=1 and club!=2 and club!=3):
      print("Escolha inválida. Tente novamente")
      club=int(input("Para Clube Social Original, digite 1; para Clube Social Presunto, digite 2; para Clube Social Pizza, digite 3"))
    if(club==1):
      print("Você escolheu Clube Social Original")
      orig=orig+1
    elif(club==2):
      print("Você escolheu Clube Social Presunto")
      pres=pres+1
    elif(club==3):
      print("Você escolheu Clube Social Pizza")
      pizza=pizza+1
    club=int(input("Segundo pacote. Para Clube Social Original, digite 1; para Clube Social Presunto, digite 2; para Clube Social Pizza, digite 3"))
    while(club!=1 and club!=2 and club!=3):
      print("Escolha inválida. Tente novamente")
      club=int(input("Para Clube Social Original, digite 1; para Clube Social Presunto, digite 2; para Clube Social Pizza, digite 3"))
    if(club==1):
      print("Você escolheu Clube Social Original")
      orig=orig+1
    elif(club==2):
      print("Você escolheu Clube Social Presunto")
      pres=pres+1
    elif(club==3):
      print("Você escolheu Clube Social Pizza")
      pizza=pizza+1
  print("Agora é a hora de escolher as bebidas")
  bebida=int(input("Para Gatorade Uva, digite 1; para Gatorade Laranja, digite 2; para Gatorade Limão, digite 3; para Gatorade Tangerina, digite 4; para Gatorade Morango-Maracujá, digite 5; para Gatorade Maracujá, digite 6; para Gatorade Frutas Cítricas, digite 7"))
  while(bebida!=1 and bebida!=2 and bebida!=3 and bebida!=4 and bebida!=5 and bebida!=6 and bebida!=7):
    print("Escolha inválida. Tente novamente")
    bebida=int(input("Para Gatorade Uva, digite 1; para Gatorade Laranja, digite 2; para Gatorade Limão, digite 3; para Gatorade Tangerina, digite 4; para Gatorade Morango-Maracujá, digite 5; para Gatorade Maracujá, digite 6; para Gatorade Frutas Cítricas, digite 7"))
  if(bebida==1):
    print("Você escolheu Gatorade Uva")
    uva=uva+1
  elif(bebida==2):
    print("Você escolheu Gatorade Laranja")
    lar=lar+1
  elif(bebida==3):
    print("Você escolheu Gatorade Limão")
    lim=lim+1
  elif(bebida==4):
    print("Você escolheu Gatorade Tangerina")
    tan=tan+1
  elif(bebida==5):
    print("Você escolheu Gatorade Morango-Maracujá")
    mm=mm+1
  elif(bebida==6):
    print("Você escolheu Gatorade Maracujá")
    mar=mar+1
  elif(bebida==7):
    print("Você escolheu Gatorade Frutas Cítricas")
    fc=fc+1
  print("Agora é a hora de escolher a fruta")
  fruta=int(input("Para laranja, digite 1; para tangerina, digite 2; para maçã vermelha, digite 3; para maçã verde, digite 4; para banana, digite 5; para ameixa, digite 6; para pera, digite 7"))
  while(fruta!=1 and fruta!=2 and fruta!=3 and fruta!=4 and fruta!=5 and fruta!=6 and fruta!=7):
    print("Escolha inválida. Tente novamente")
    fruta=int(input("Para laranja, digite 1; para tangerina, digite 2; para maçã vermelha, digite 3; para maçã verde, digite 4; para banana, digite 5; para ameixa, digite 6; para pera, digite 7"))
  if(fruta==1):
    print("Você escolheu laranja")
    laranja=laranja+1
  elif(fruta==2):
    print("Você escolheu tangerina")
    tangerina=tangerina+1
  elif(fruta==3):
    print("Você escolheu maçã vermelha")
    maverm=maverm+1
  elif(fruta==4):
    print("Você escolheu maçã verde")
    maverd=maverd+1
  elif(fruta==5):
    print("Você escolheu banana")
    ban=ban+1
  elif(fruta==6):
    print("Você escolheu ameixa")
    am=am+1
  elif(fruta==7):
    print("Você escolheu pera")
    pera=pera+1
print("Total de lanches: ",lanches)
print("Número de Belvita Cacau e Cereais a comprar: ",cacau)
print("Número de Belvita Mel e Cacau a comprar: ",mel)
print("Número de Belvita Leite e Aveia a comprar: ",leite)
print("Número de Clube Social Original a comprar: ",orig)
print("Número de Clube Social Presunto a comprar: ",pres)
print("Número de Clube Social Pizza a comprar: ",pizza)
print("Número de Gatorade Uva a comprar: ",uva)
print("Número de Gatorade Laranja a comprar: ",lar)
print("Número de Gatorade Limão a comprar: ",lim)
print("Número de Gatorade Tangerina a comprar: ",tan)
print("Número de Gatorade Maracujá a comprar: ",mar)
print("Número de Gatorade Morango-Maracujá a comprar: ",mm)
print("Número de Gatorade Frutas Cítricas a comprar: ",fc)
print("Número de laranjas a comprar: ",laranja)
print("Número de tangerinas a comprar: ",tangerina)
print("Número de maçãs vermelhas a comprar: ",maverm)
print("Número de maçãs verdes a comprar: ",maverd)
print("Número de bananas a comprar: ",ban)
print("Número de ameixas a comprar: ",am)
print("Número de peras a comprar: ",pera)

#2. Crie um código para determinar se o ano x é bissexto ou não. Dica: você pode usar os condicionais(if, elif, else e and)
y=0
x=int(input("Digite um ano para saber se ele é bissexto:"))
while(x<0):
  print("Ano inválido. Tente novamente")
  x=int(input("Digite um ano para saber se ele é bissexto:"))
if(x%4==0 and x%100!=0 or x%400==0):
      print("O ano",x,"é bissexto")
else:
  print("O ano",x,"não é bissexto")

#3. Crie um código para determinar se o número x é primo ou não. Dica: você pode usar listas e os condicionais(if, elif, else e or)
x=int(input("Insira um número:"))
y=0

for a in range(1,x+1):
  if(x%a==0):
    y=y+1
if(y==2):
  print("Seu número é primo")
else:
  print("Seu número não é primo")

#4. Crie um código para determinar sua nota na matéria de GeoInformática. Dica: você pode usar float
nota=float(input("Insira a nota que você quer tirar em GeoInformática:"))
while(nota<0 or nota>10):
  print("Nota inválida. Tente novamente")
  nota=float(input("Insira a nota que você quer tirar em GeoInformática:"))
ChicoVictorLuizDIVOS=int(input("Chico, Victor e Luiz são divos? Responda com 1 para sim ou 0 para não:"))
while(ChicoVictorLuizDIVOS!=1 and ChicoVictorLuizDIVOS!=0):
  print("Valor inválido. Tente novamente")
  ChicoVictorLuizDIVOS=int(input("Chico, Victor e Luiz são divos? Responda com 1 para sim ou 0 para não:"))
if(ChicoVictorLuizDIVOS==0):
  print("Sua nota em GeoInformática é: ",nota-0.1)
else:
  print("Sua nota em GeoInformática é: ",nota)

"""#Execicíos bônus
-A empresa CHICO LTDA está interessada na caracterização geológica da região para implementação de um projeto de exploração. Para isso, a empresa alocou poços no terreno de interesse, visando caracterizar litologicamente a subsuperfície, obtendo os seguintes resultados fictícios:

Poço 1: Basalto Arenito Folhelho Arenito Diabásio Folhelho

Poço 2: Arenito Conglomerado Folhelho Arenito Folhelho

Poço 3: Basalto Diabásio Gabro

-Seus chefes pediram para você analisar os 3 poços, de forma veloz, e querem saber:

A) Existe algum poço somente rocha sedimentar?

B) Existe algum poço que apresenta rocha sedimentar ou ígnea?

C) Existe algum poço que apresenta rocha sedimentar e ígnea?
"""

Conglo,msedimentar1=ignea1=sedimentar2=ignea2=sedimentar3=ignea3=0
listapoco1=[0]*10
listapoco2=[0]*10
listapoco3=[0]*10
poco1=int(input("Quantas camadas têm o poço 1?"))
for a in range(1,poco1+1):
  listapoco1[a]=input(f"Insira a camada {a} do poço 1:")
  if(listapoco1[a]=="Arenito" or listapoco1[a]=="Folhelho" or listapoco1[a]=="Conglomerado"):
    sedimentar1=sedimentar1+1
  if(listapoco1[a]=="Basalto" or listapoco1[a]=="Diabásio" or listapoco1[a]=="Gabro"):
    ignea1=ignea1+1
if(poco1!=0 and poco1==sedimentar1):
  print("O poço 1 apresenta apenas rocha sedimentar")
elif(poco1!=0 and poco1==ignea1):
  print("O poço 1 apresenta apenas rocha ígnea")
elif(poco1!=0 and sedimentar1>0 and ignea1>0):
  print("O poço 1 apresenta rocha sedimentar e ígnea")
elif(poco1!=0 and sedimentar1>0 or ignea1>0):
  print("O poço 1 apresenta rocha sedimentar ou ígnea")
elif(poco1!=0 and sedimentar1==0 and ignea1==0):
  print("O poço 1 não apresenta rocha sedimentar nem ígnea")
poco2=int(input("Quantas camadas têm o poço 2?"))
for b in range(1,poco2+1):
  listapoco2[b]=input(f"Insira a camada {b} do poço 2:")
  if(listapoco2[b]=="Arenito" or listapoco2[b]=="Folhelho" or listapoco2[b]=="Conglomerado"):
    sedimentar2=sedimentar2+1
  if(listapoco2[b]=="Basalto" or listapoco2[b]=="Diabásio" or listapoco2[b]=="Gabro"):
    ignea2=ignea2+1
if(poco2!=0 and poco2==sedimentar2):
  print("O poço 2 apresenta apenas rocha sedimentar")
elif(poco2!=0 and poco2==ignea2):
  print("O poço 2 apresenta apenas rocha ígnea")
elif(poco2!=0 and sedimentar2>0 and ignea2>0):
  print("O poço 2 apresenta rocha sedimentar e ígnea")
elif(poco2!=0 and sedimenta2r>0 or ignea2>0):
  print("O poço 2 apresenta rocha sedimentar ou ígnea")
elif(poco2!=0 and sedimentar2==0 and ignea2==0):
  print("O poço 2 não apresenta rocha sedimentar nem ígnea")
poco3=int(input("Quantas camadas têm o poço 3?"))
for c in range(1,poco3+1):
  listapoco3[c]=input(f"Insira a camada {c} do poço 3:")
  if(listapoco3[c]=="Arenito" or listapoco3[c]=="Folhelho" or listapoco3[c]=="Conglomerado"):
    sedimentar3=sedimentar3+1
  if(listapoco3[c]=="Basalto" or listapoco3[c]=="Diabásio" or listapoco3[c]=="Gabro"):
    ignea3=ignea3+1
if(poco3!=0 and poco3==sedimentar3):
  print("O poço 3 apresenta apenas rocha sedimentar")
elif(poco3!=0 and poco3==ignea3):
  print("O poço 3 apresenta apenas rocha ígnea")
elif(poco3!=0 and sedimentar3>0 and ignea3>0):
  print("O poço 3 apresenta rocha sedimentar e ígnea")
elif(poco3!=0 and sedimentar3>0 or ignea3>0):
  print("O poço 3 apresenta rocha sedimentar ou ígnea")
elif(poco3!=0 and sedimentar3==0 and ignea3==0):
  print("O poço 3 não apresenta rocha sedimentar nem ígnea")