# -*- coding: utf-8 -*-
"""Maria Eduarda Francklim - Lista 2 Monitoria Geoinformática.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8bOcV1aL8bJYGNGyze05aBiIm0HxO_W

#Exercícios aula 2

- Precedência de operações: quais operações serão realizadas primeiro em uma operação; PEMDAS

Parêntese

Elevado

Multiplicação

Divisão

Adição

Subtração

- Condicionais: if, else e elif

If - "se" para quando a condicional for atendida

Else - "se não" quando a condicional não for atendida

Elif - mesma função do "else", pode ser usado repetidas vezes
"""

#1. Sabendo que números primos são aqueles divididos apenas por 1 e ele mesmo, monte um código que informa se o valor de x é primo.
x=int(input("Insira um número:"))
y=0

for a in range(1,x+1):
  if(x%a==0):
    y=y+1
if(y==2):
  print("Seu número é primo")
else:
  print("Seu número não é primo")

#2. Monte um código que informa se o valor de x é par ou impar.
x=int(input("Insira um número:"))
if(x==0):
  print("Seu número não é par nem ímpar")
if(x%2==0 and x!=0):
  print("Seu número é par")
if(x%2!=0 and x!=0): print("Seu número é ímpar")

#3. Você recebeu um perfil de 50 metros de um afloramento. Nos primeiros 15 metros existe uma camada de folhelho, depois 10 metros de uma camada de arenito e nos ultimos 25 metros uma camada de conglomerado.
#Crie um codigo onde o x representa a altura em metros nesse perfil, e que ele tenha na saida a litologia do afloramento.
y=50
x=float(input("Insira a metragem sobre a qual você quer conhecer a litologia:"))
if(0<=x and x<=15):
  print(f"A litologia no metro {x} é folhelho")
elif(15<x and x<=25):
  print(f"A litologia no metro {x} é arenito")
elif(25<x and x<=50):
  print(f"A litologia no metro {x} é conglomerado")
elif(x<0 or x>y):
  print(f"A metragem {x} é inválida")

#4.a. Resolva a equação utilizando () de forma a obter 0: 56-36/6**6-5*7-50*4/10
print(int((56-(36/(6**6)))-(5*7)-((50*4)/10)))

#4.b. Resolva a equação utilizando apenas váriavel de forma a obter 0: 56-36/6**2-5*7-50*4/10
a=56
b=6
c=2
d=36
e=5
f=7
g=50
h=c*e
v=b**c
w=d/v
x=e*f
y=g*c*c
z=y/h

print(a-w-x-z)